Plugin-Update to Mautic3
Leuchtfeuer/auth0-for-mautic pull request #4
Opened 2020-09-07 12:12 UTC by luguenth

User-Facing changes:
The Callback-URL has to be altered. The new Callback-URL is ending in "Auth0" instead of "Auth0Auth"

2020-09-26 09:10 UTC, flossels reviewed
Hi Lukas,

there are some things you should change before I will merge this PR.

2020-09-26 09:10 UTC, flossels commented on README.md
> +Auth0 for Mautic 3
Please do not harden the version number here as this plugin is in older versions still available for versions prior to Mautic 3.

2020-09-26 09:10 UTC, flossels commented on README.md
> +When Updating the Plugin, you have to make sure to change the Callback-URL(s) in Auth0.
You can simplify this lines by just writing:
When updating the plugin, please make sure to change the callback URL from `../s/sso_login/Auth0Auth` to `../s/sso_login/Auth0` in your Auth0 application settings.

2020-09-26 09:10 UTC, flossels commented on Config/config.php
> +                'arguments' => [
Are all these arguments really necessary?

2020-09-26 09:10 UTC, flossels commented on Integration/Auth0Integration.php
> +        // Just use none for now and I'll build in "basic" later
???

2020-09-26 09:10 UTC, flossels commented on Integration/Auth0Integration.php
> +    public function getAuthCallbackUrl()
This can be archived by using `sprintf()` only.

2020-09-26 09:20 UTC, flossels requested changes
request changes.

2020-09-30 06:46 UTC, flossels requested changes
There is an issue with the file permissions which are partially changed from 0644 to 0755

2020-11-05 13:19 UTC, flossels commented
@luguenth any news on this?

2020-11-06 08:14 UTC, luguenth commented on Config/config.php
> +                'arguments' => [
yes unfortunately :cry:

2020-11-06 18:05 UTC, flossels approved these changes

2020-11-06 18:06 UTC, merged